nelmio_api_doc:
    documentation:
        info:
            title: 'Organization API'
            description: 'Документация для API по управлению организациями, зданиями и видами деятельности.'
            version: '1.0.0'
    areas:
        default:
            path_patterns:
                - ^/api/organization
    models:
        names: []
        use_jms: false
