version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nebus_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    expose:
      - "9000" # PHP-FPM порт для взаимодействия с Nginx
    environment:
      APP_ENV: dev
      DATABASE_URL: postgres://symfony:symfony@db:5432/symfony

  nginx:
    image: nginx:latest
    container_name: nebus_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: postgres:17
    container_name: nebus_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
